"""
Leakage-safe feature engineering module for Experiment 07 Recommendation System.
Computes customer, item, and user-item interaction signals strictly from historical transactions before cutoff.
"""

from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# Comprehensive feature dictionary definitions
FEATURE_DEFINITIONS: Dict[str, Dict[str, str]] = {
    "cust_txns": {
        "description": "Total number of distinct historical orders completed by the customer.",
        "level": "Customer",
        "computation": "hist.groupby(user_col)[order_col].nunique()",
    },
    "cust_items": {
        "description": "Total number of distinct products previously bought by the customer.",
        "level": "Customer",
        "computation": "hist.groupby(user_col)[item_col].nunique()",
    },
    "cust_qty": {
        "description": "Total quantity of product units purchased across customer history.",
        "level": "Customer",
        "computation": "hist.groupby(user_col)['quantity'].sum()",
    },
    "cust_spend": {
        "description": "Total historical monetary expenditure by the customer.",
        "level": "Customer",
        "computation": "hist.groupby(user_col)[amount_col].sum()",
    },
    "cust_recency_days": {
        "description": "Elapsed days between the customer's last purchase and the temporal cutoff.",
        "level": "Customer",
        "computation": "(cutoff - max(ts)).dt.days",
    },
    "cust_avg_basket_spend": {
        "description": "Average expenditure per order for the customer.",
        "level": "Customer",
        "computation": "cust_spend / cust_txns",
    },
    "cust_avg_basket_size": {
        "description": "Average item count per order for the customer.",
        "level": "Customer",
        "computation": "cust_qty / cust_txns",
    },
    "item_txns": {
        "description": "Total number of distinct historical orders containing this item.",
        "level": "Item",
        "computation": "hist.groupby(item_col)[order_col].nunique()",
    },
    "item_buyers": {
        "description": "Number of distinct customers who historically purchased this item.",
        "level": "Item",
        "computation": "hist.groupby(item_col)[user_col].nunique()",
    },
    "item_qty": {
        "description": "Total units of this item sold historically.",
        "level": "Item",
        "computation": "hist.groupby(item_col)['quantity'].sum()",
    },
    "item_spend": {
        "description": "Total historical revenue generated by this item.",
        "level": "Item",
        "computation": "hist.groupby(item_col)[amount_col].sum()",
    },
    "item_avg_price": {
        "description": "Average realized unit price for this item.",
        "level": "Item",
        "computation": "item_spend / max(item_qty, 1)",
    },
    "item_recency_days": {
        "description": "Elapsed days between this item's last sale and the temporal cutoff.",
        "level": "Item",
        "computation": "(cutoff - max(ts)).dt.days",
    },
    "item_repeat_rate": {
        "description": "Fraction of buyers who purchased this item more than once.",
        "level": "Item",
        "computation": "P(buyer_orders > 1 | buyer)",
    },
    "pair_purchases": {
        "description": "Number of previous orders where this customer purchased this item.",
        "level": "Customer-Item",
        "computation": "hist.groupby([user_col, item_col])[order_col].nunique()",
    },
    "pair_qty": {
        "description": "Total units of this item previously bought by this customer.",
        "level": "Customer-Item",
        "computation": "hist.groupby([user_col, item_col])['quantity'].sum()",
    },
    "pair_spend": {
        "description": "Total spend by this customer on this specific item.",
        "level": "Customer-Item",
        "computation": "hist.groupby([user_col, item_col])[amount_col].sum()",
    },
    "pair_recency_days": {
        "description": "Elapsed days since customer last bought this item (or fallback 999.0).",
        "level": "Customer-Item",
        "computation": "(cutoff - max(pair_ts)).dt.days",
    },
    "pair_repeat_indicator": {
        "description": "Binary flag indicating if customer previously bought this item >= 2 times.",
        "level": "Customer-Item",
        "computation": "int(pair_purchases >= 2)",
    },
    "pair_spend_share": {
        "description": "Share of customer total spend dedicated to this item.",
        "level": "Customer-Item",
        "computation": "pair_spend / max(cust_spend, 1.0)",
    },
}


def customer_features(
    hist: pd.DataFrame,
    cutoff: pd.Timestamp,
    user_col: str = "user_id",
    order_col: str = "order_id",
    item_col: str = "item_id",
    amount_col: str = "amount",
    ts_col: str = "ts",
) -> pd.DataFrame:
    """
    Compute customer-level behavioral and RFM features strictly from historical data before cutoff.
    """
    g = hist.groupby(user_col)
    cust_df = g.agg(
        cust_txns=(order_col, "nunique"),
        cust_items=(item_col, "nunique"),
        cust_qty=("quantity", "sum") if "quantity" in hist.columns else (amount_col, "count"),
        cust_spend=(amount_col, "sum"),
        cust_last=(ts_col, "max"),
    ).reset_index()

    cust_df["cust_recency_days"] = np.maximum(
        (cutoff - cust_df["cust_last"]).dt.total_seconds() / 86400.0, 0.0
    )
    cust_df["cust_avg_basket_spend"] = cust_df["cust_spend"] / np.maximum(
        cust_df["cust_txns"], 1.0
    )
    cust_df["cust_avg_basket_size"] = cust_df["cust_qty"] / np.maximum(
        cust_df["cust_txns"], 1.0
    )

    return cust_df.drop(columns=["cust_last"])


def item_features(
    hist: pd.DataFrame,
    cutoff: pd.Timestamp,
    item_col: str = "item_id",
    order_col: str = "order_id",
    user_col: str = "user_id",
    amount_col: str = "amount",
    ts_col: str = "ts",
) -> pd.DataFrame:
    """
    Compute item-level popularity, pricing, and repeat purchase features strictly from historical data.
    """
    g = hist.groupby(item_col)
    item_df = g.agg(
        item_txns=(order_col, "nunique"),
        item_buyers=(user_col, "nunique"),
        item_qty=("quantity", "sum") if "quantity" in hist.columns else (amount_col, "count"),
        item_spend=(amount_col, "sum"),
        item_last=(ts_col, "max"),
    ).reset_index()

    item_df["item_avg_price"] = item_df["item_spend"] / np.maximum(item_df["item_qty"], 1.0)
    item_df["item_recency_days"] = np.maximum(
        (cutoff - item_df["item_last"]).dt.total_seconds() / 86400.0, 0.0
    )

    # Compute item repeat-buyer rate: fraction of buyers with > 1 orders of this item
    buyer_orders = hist.groupby([item_col, user_col])[order_col].nunique().reset_index()
    repeat_buyers = (
        buyer_orders[buyer_orders[order_col] > 1]
        .groupby(item_col)[user_col]
        .nunique()
        .reset_index(name="repeat_buyer_count")
    )
    item_df = item_df.merge(repeat_buyers, on=item_col, how="left")
    item_df["repeat_buyer_count"] = item_df["repeat_buyer_count"].fillna(0)
    item_df["item_repeat_rate"] = item_df["repeat_buyer_count"] / np.maximum(
        item_df["item_buyers"], 1.0
    )

    return item_df.drop(columns=["item_last", "repeat_buyer_count"])


def pair_features(
    hist: pd.DataFrame,
    cutoff: pd.Timestamp,
    user_col: str = "user_id",
    item_col: str = "item_id",
    order_col: str = "order_id",
    amount_col: str = "amount",
    ts_col: str = "ts",
) -> pd.DataFrame:
    """
    Compute customer-item affinity and interaction features strictly from historical data.
    """
    g = hist.groupby([user_col, item_col])
    pair_df = g.agg(
        pair_purchases=(order_col, "nunique"),
        pair_qty=("quantity", "sum") if "quantity" in hist.columns else (amount_col, "count"),
        pair_spend=(amount_col, "sum"),
        pair_last=(ts_col, "max"),
    ).reset_index()

    pair_df["pair_recency_days"] = np.maximum(
        (cutoff - pair_df["pair_last"]).dt.total_seconds() / 86400.0, 0.0
    )
    pair_df["pair_repeat_indicator"] = (pair_df["pair_purchases"] >= 2).astype(int)

    return pair_df.drop(columns=["pair_last"])


def build_feature_matrix(
    pairs_df: pd.DataFrame,
    cust_feats: pd.DataFrame,
    item_feats: pd.DataFrame,
    pair_feats: pd.DataFrame,
    user_col: str = "user_id",
    item_col: str = "item_id",
) -> Tuple[pd.DataFrame, List[str]]:
    """
    Join customer, item, and pair features onto candidate pairs with leak-free null imputations.

    Returns:
        X: Feature matrix DataFrame with user_id, item_id, and all engineered numerical features.
        feature_cols: List of column names used as numerical model features.
    """
    # Ensure join keys are uniform strings
    pairs = pairs_df.copy()
    pairs[user_col] = pairs[user_col].astype(str)
    pairs[item_col] = pairs[item_col].astype(str)

    cf = cust_feats.copy()
    cf[user_col] = cf[user_col].astype(str)

    it = item_feats.copy()
    it[item_col] = it[item_col].astype(str)

    pf = pair_feats.copy()
    pf[user_col] = pf[user_col].astype(str)
    pf[item_col] = pf[item_col].astype(str)

    # Left join customer, item, and pair blocks
    m = pairs.merge(cf, on=user_col, how="left")
    m = m.merge(it, on=item_col, how="left")
    m = m.merge(pf, on=[user_col, item_col], how="left")

    # Safe null imputations for unobserved customer/item/pair interactions
    # Pair features: customer has never bought this item previously
    m["pair_purchases"] = m["pair_purchases"].fillna(0.0)
    m["pair_qty"] = m["pair_qty"].fillna(0.0)
    m["pair_spend"] = m["pair_spend"].fillna(0.0)
    m["pair_repeat_indicator"] = m["pair_repeat_indicator"].fillna(0.0)
    m["pair_recency_days"] = m["pair_recency_days"].fillna(999.0)

    # Customer features fallback (for cold/unobserved customers)
    m["cust_txns"] = m["cust_txns"].fillna(0.0)
    m["cust_items"] = m["cust_items"].fillna(0.0)
    m["cust_qty"] = m["cust_qty"].fillna(0.0)
    m["cust_spend"] = m["cust_spend"].fillna(0.0)
    m["cust_recency_days"] = m["cust_recency_days"].fillna(999.0)
    m["cust_avg_basket_spend"] = m["cust_avg_basket_spend"].fillna(0.0)
    m["cust_avg_basket_size"] = m["cust_avg_basket_size"].fillna(0.0)

    # Item features fallback
    m["item_txns"] = m["item_txns"].fillna(0.0)
    m["item_buyers"] = m["item_buyers"].fillna(0.0)
    m["item_qty"] = m["item_qty"].fillna(0.0)
    m["item_spend"] = m["item_spend"].fillna(0.0)
    m["item_avg_price"] = m["item_avg_price"].fillna(0.0)
    m["item_recency_days"] = m["item_recency_days"].fillna(999.0)
    m["item_repeat_rate"] = m["item_repeat_rate"].fillna(0.0)

    # Cross-level interaction feature: share of customer spend on this item
    m["pair_spend_share"] = m["pair_spend"] / np.maximum(m["cust_spend"], 1.0)
    m["pair_spend_share"] = m["pair_spend_share"].fillna(0.0)

    feature_cols = [
        "cust_txns",
        "cust_items",
        "cust_qty",
        "cust_spend",
        "cust_recency_days",
        "cust_avg_basket_spend",
        "cust_avg_basket_size",
        "item_txns",
        "item_buyers",
        "item_qty",
        "item_spend",
        "item_avg_price",
        "item_recency_days",
        "item_repeat_rate",
        "pair_purchases",
        "pair_qty",
        "pair_spend",
        "pair_recency_days",
        "pair_repeat_indicator",
        "pair_spend_share",
    ]

    # Acceptance check: strictly zero NaNs permitted in feature matrix
    if m[feature_cols].isna().any().any():
        nan_cols = m[feature_cols].columns[m[feature_cols].isna().any()].tolist()
        raise AssertionError(f"Appendix C violation: feature columns contain NaNs: {nan_cols}")

    return m, feature_cols


def feature_dictionary(feature_cols: List[str]) -> pd.DataFrame:
    """
    Generate standard feature dictionary DataFrame with descriptions, source levels, and computation logic.
    """
    rows = []
    for f in feature_cols:
        info = FEATURE_DEFINITIONS.get(
            f,
            {
                "description": "Engineered numerical interaction feature.",
                "level": "Derived",
                "computation": "N/A",
            },
        )
        rows.append(
            {
                "feature_name": f,
                "level": info["level"],
                "description": info["description"],
                "computation": info["computation"],
            }
        )
    return pd.DataFrame(rows)
